branches:
  only:
  - master
language: node_js
cache:
  directories:
  - node_modules
  yarn: true
node_js:
- 9
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  firefox: stable
env:
  - MOZ_HEADLESS=1
script:
- yarn run test
- yarn run build
- yarn run start &
- yarn run jest -c e2e.config.js
