branches:
  only:
  - master
language: node_js
cache:
  directories:
  - node_modules
  yarn: true
node_js:
- 9
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  firefox: latest
env:
  - MOZ_HEADLESS=1
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
script:
- yarn run test
- yarn run build
- yarn run start &
- yarn run jest -c e2e.config.js
